### ISSUE TITLE
Funding Request - Release 71.0.0

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2578]
As always a **big thank you** to those who have contributed previously and especially those who make  recurring contributions through [BountySource Salt](https://salt.bountysource.com/teams/cefsharp).

Shortly the time will come where I'll ask for funding towards releasing a `71.0.0` set of `Nuget` packages. As some of you may well know I'm currently a stay at home dad and spend a fairly large amount of time (roughly `10-12hrs` per week) developing and supporting the project. Your contributions are the only reason I'm allowed to continue working on the project. Without continued funding the time I currently spend on the project will have to be put into finding other paid work.

There are multiple options for contributing at this time:

- Contribute an amount towards the Bounty on this issue [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=66538061)](https://www.bountysource.com/issues/66538061-funding-request-release-71-0-0?utm_source=66538061&utm_medium=shield&utm_campaign=ISSUE_BADGE)
- Recurring contribution through [BountySource Salt](https://salt.bountysource.com/teams/cefsharp)
- Recurring contribution through [Patreon](https://www.patreon.com/alexmaitland)
- A one time contribution through [BountySource](https://www.bountysource.com/teams/cefsharp)
- A one time contribution through `Paypal` at https://paypal.me/AlexMaitland

If you'd like to made a donation through Paypal directly, I'll happily reduce the target accordingly.

## Release 71.0.0-pre01
**When 50% of target reached**
  - [x] `AppVeyor` builds for `cef-binary` are currently failing so unable to upgrade to newer `CEF` version until https://github.com/cefsharp/cef-binary/issues/70 has been resolved  
  - [x] Update `master` to `CEF  3578 branch` build
  - [x] Add Chrome Extension Support #2497
  - [x] Add CefRenderHandler::OnAcceleratedPaint #2527
  - [x] Investigate changes required for Chromium Site Isolation #2553
  - [x] Create `cefsharp/71` release branch
  - [x] Update changelog and create release notes
  - [x] Release 71.0.0-pre01 packages to nuget.org

## Release 71.0.0
**When 100% of target reached**
  - [x] Resolve remaining issues attached to [71 Milestone](https://github.com/cefsharp/CefSharp/milestone/38)
  - [x] Add note about removing WinForms workaround in https://github.com/cefsharp/CefSharp/commit/821a44fecc9aa1e103027323defea7b1d4c0bf82
  - [x] Update changelog and create release notes
  - [x] Generate new `API Doc` and upload to http://cefsharp.github.io/api/ 
  - [x] Release 71.0.0 pacakges to nuget.org
  

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=66538061)](https://www.bountysource.com/issues/66538061-funding-request-release-71-0-0?utm_source=66538061&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by AgapovAlexsey** [comment]
@amaitland Is it possible to indicate the wishes that I am ready to support?

**Comment by amaitland** [comment]
@AgapovAlexsey You are welcome to features you are interested in and we can discuss their feasibility and the amount of time required.

**Comment by AluminiumTech** [comment]
What happened to re-launching a Patreon after the initial one didn't work out?

**Comment by amaitland** [comment]
> What happened to re-launching a Patreon after the initial one didn't work out?

@AluminiumTech I did have a look into it, did some searching to see if my unfortunate interaction with `Patreon` was an isolated incident and I found multiple reports of exactly the same thing. The following links paint a concerning picture in my opinion.

https://www.reddit.com/r/patreon/comments/7hvfcd/suspended_account/
https://www.reddit.com/r/patreon/comments/94gbek/patreon_banned_my_account_for_suspected_fraud_and/
https://www.reddit.com/r/patreon/comments/6exo1f/unable_to_get_a_reply_from_support_from_patreon/

**Comment by AluminiumTech** [comment]
> @AluminiumTech I did have a look into it, did some searching to see if my unfortunate interaction with Patreon was an isolated incident and I found multiple reports of exactly the same thing. The following links paint a concerning picture in my opinion.

> https://www.reddit.com/r/patreon/comments/7hvfcd/suspended_account/
https://www.reddit.com/r/patreon/comments/94gbek/patreon_banned_my_account_for_suspected_fraud_and/
https://www.reddit.com/r/patreon/comments/6exo1f/unable_to_get_a_reply_from_support_from_patreon/


I'm not gonna lie, those are some quite major issues they had a while back. However, they do seem to be quite isolated.

As a Patron I've never had an issue with Patreon and I think that aside from those isolated cases, Patreon as a platform works. I'm not defending Patreon as they should have handled those situations better but I do think you're not giving Patreon the chance it deserves.

I would recommend looking into re-launching with a more positive attitude and give them another chance.

**Comment by amaitland** [comment]
> I'm not gonna lie, those are some quite major issues they had a while back. However, they do seem to be quite isolated.

@AluminiumTech  For clarity, they banned my account for `suspected fraudulent activity`. Refused to discuss the situation, provided no details on the rules I had breached (if any). I'm merely pointing out that I'm not alone.

**Comment by amaitland** [comment]
@AluminiumTech I've created a new `Patreon` account at https://www.patreon.com/alexmaitland

Will give it one more chance.

**Comment by amaitland** [comment]
`BountSource` isn't showing the current target so just for clarity it's currently `$850USD` (Which after payment processing fees is roughly the amount I need to get my `Car Air-conditioning` repaired).

**Comment by netherspite** [comment]
Sent 100 EUR :)
Keep up the good work :)

**Comment by amaitland** [comment]
@netherspite Thank you for the very generous contribution 😄 Greatly appreciated.

**Comment by amaitland** [comment]
`Chrome` extension support is almost complete, only a few minor things to resolve before #2613 is merged and the first `-pre` release will be out. Should hopefully be finished tomorrow.

**Comment by amaitland** [comment]
A huge thank you to all those who have contributed through `BountySource` and directly through `Paypal`! Adding up all the contributions and the target has now been met! 🍾 🎆 👍

**Comment by amaitland** [comment]
[cefsharp/71](https://github.com/cefsharp/CefSharp/tree/cefsharp/71) branch has been created, the `Nuget` packages for the `-pre` release will be created soon as I've got the `Release Notes` in order. Should be tomorrow.

From this point on `Breaking changes` will only be made if absolutely necessary.

**Comment by amaitland** [comment]
The `71.0.0-pre01` packages have been pushed to `Nuget.org`, it'll take a little while before they appear.

https://www.nuget.org/packages/CefSharp.Wpf/71.0.0-pre01
https://www.nuget.org/packages/CefSharp.OffScreen/71.0.0-pre01
https://www.nuget.org/packages/CefSharp.WinForms/71.0.0-pre01

The `MinimalExample` has been upgraded, see 
https://github.com/cefsharp/CefSharp.MinimalExample/tree/cefsharp/71 (branch will be merged into `master` upon final release). You can use this for testing purposes.

**Comment by amaitland** [comment]
The last of the issues attached to the `71.0.0` milestone has been closed, for anyone interested you can check out https://github.com/cefsharp/CefSharp/compare/v71.0.0-pre01...cefsharp/71 to see what's changed since the `-pre` release.

Unless there are any show stopping bugs reported in the next week I'll release the final `71.0.0` packages next week.

**Comment by amaitland** [comment]
`CEF` has updated to `Chromium version 71.0.3578.98`, will look at updating before the official release, should only be bug fixes.

https://bitbucket.org/chromiumembedded/cef/commits/bf8cff263c07bd74cf57050d755fb48a8cde00fc?at=3578

**Comment by amaitland** [comment]
`cefsharp/71` branch has been upgraded to `CEF 3.3578.1863.gbf8cff2 / Chromium 71.0.3578.98`

**Comment by amaitland** [comment]
The `3578` branch has been updated again with a minor fixed outlined in https://bitbucket.org/chromiumembedded/cef/issues/2561/1218-134345786639-fatal

Unless someone is absolutely desperate I'll wait until a build appears and upgrade to the latest `CEF` version. This will delay the `71.0.0` release by about 2 days (have to wait for the build to appear). 

Any objections to this plan please make them known.

**Comment by amaitland** [comment]
The `CEF 3.3578.1864.gfa073f3 / Chromium 71.0.3578.98` build is only available in an `x86` version, so rather than delay further for an issue that is unlikely to cause problems to `99%` of people I've decided to go ahead with the `CEF 3.3578.1863.gbf8cff2 / Chromium 71.0.3578.98` build.

The `71.0.0` packages have been pushed to `Nuget.org` and should appear shortly. The `MinimalExample` has been upgraded, see https://github.com/cefsharp/CefSharp.MinimalExample

Will leave this open for a little while before closing.
