### ISSUE TITLE
Funding Request - Release 73.0.0

### ISSUE THREAD

**Issue by amaitland** [cefsharp/CefSharp#2696]
As always a **big thank you** to those who have contributed previously and especially those who make  recurring contributions through [BountySource Salt](https://salt.bountysource.com/teams/cefsharp).

Shortly the time will come where I'll ask for funding towards releasing a `73.0.0` set of `Nuget` packages. As some of you may well know I'm currently a stay at home dad and spend a fairly large amount of time (roughly `10-12hrs` per week) developing and supporting the project. Your contributions are the only reason I'm allowed to continue working on the project. Without continued funding the time I currently spend on the project will have to be put into finding other paid work.

There are multiple options for contributing at this time:

- Contribute an amount towards the Bounty on this issue [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=71596940)](https://www.bountysource.com/issues/71596940-funding-request-release-73-0-0?utm_source=71596940&utm_medium=shield&utm_campaign=ISSUE_BADGE)
- Recurring contribution through [BountySource Salt](https://salt.bountysource.com/teams/cefsharp)
- Recurring contribution through [Patreon](https://www.patreon.com/alexmaitland)
- A one time contribution through [BountySource](https://www.bountysource.com/teams/cefsharp)
- A one time contribution through `Paypal` at https://paypal.me/AlexMaitland

If you'd like to made a donation through Paypal directly, I'll happily reduce the target accordingly.

The milestone is https://github.com/cefsharp/CefSharp/issues?utf8=%E2%9C%93&q=milestone%3A73.0.0+

## Release 73.0.0-pre01
  - [x] Upgrade `cef-binary` to support new `CEF` version number format https://github.com/cefsharp/cef-binary/issues/76
  - [x] Add IRenderHandler.OnVirtualKeyboardRequested #2689
  - [x] Add IDisplayHandler.OnLoadingProgressChange #2686
  - [x] Add IBrowserHost.SendTouchEvent #2663
  - [x] Update Nuget Package format #2706

## Release 73.0.0
**When 100% of target reached**
  - [x] Resolve remaining issues attached to [73 Milestone](https://github.com/cefsharp/CefSharp/milestone/39)
  - [x] Update changelog and create release notes
  - [x] Generate new `API Doc` and upload to http://cefsharp.github.io/api/ 
  - [x] Release 73.0.0 pacakges to nuget.org

**Comment by amaitland** [comment]
`CEF` has changed the format of it's builds, we have to update our build scripts accordingly see https://github.com/cefsharp/cef-binary/issues/76

**Comment by amaitland** [comment]
The `Nuget` package version numbers will be changing as `CEF` has updated it's version numbering scheme. See #2706 for details.

The first part of the version number will be updated to reflect the `CEF` version, the first `-pre` release will likely be `73.1.12.0-pre01`

**Comment by ByErdem** [comment]
I looked the support list. Really very low. Aren't there any strong supporter? This man really doing very big works and he is getting very little money. Is that justice?

**Comment by puresimmer** [comment]
$10/mo here :)

**Comment by Sankra** [comment]
Just donated 250 USD. Keep up the good work!

**Comment by amaitland** [comment]
@puresimmer @Sankra Thank you both, greatly appreciated 👍

**Comment by amaitland** [comment]
Update on the `-pre` release, I was hoping that `CEF` would have updated to a newer `Chromium` version by now, unfortunately that hasn't happened yet. So rather than delay any further I'll be releasing the first `-pre` release in the next day or two (hopefully later today).

**Comment by amaitland** [comment]
The release has been tagged see https://github.com/cefsharp/CefSharp/releases/tag/v73.1.120-pre01

The packages are on the `MyGet` feed currently, they still need a little more testing as I'm seeing a `GPU Process` crash on my local machine. Will update when I know more.

**Comment by amaitland** [comment]
> they still need a little more testing as I'm seeing a `GPU Process` crash on my local machine. Will update when I know more.

Silly mistake on my part, problem resolved. 

The `73.1.120-pre01` packages have been pushed to `Nuget.org` they should appear shortly. Note the new versioning scheme. See #2706 for details on the version scheme change.

**Comment by amaitland** [comment]
Just posted https://magpcss.org/ceforum/viewtopic.php?f=10&t=16718 hopefully get a response in the next few days regarding upgrading CEF to the latest 73 stable chromium version.

**Comment by amaitland** [comment]
Appears there won't be any further updates to the `3683` branch, so will release based on `CEF 73.1.13+g6e3c989+chromium-73.0.3683.75 / Chromium 73.0.3683.75`

I should hopefully have #2727 sorted in the next day or two, then the rest is house keeping. Should be a final release end of week.

**Comment by amaitland** [comment]
`API` doc has been generated and is up at http://cefsharp.github.io/api/73.1.x/

**Comment by amaitland** [comment]
The `73.1.130` packages have been pushed to `Nuget.org` and should appear shortly. The `MinimalExample` has been upgraded, see https://github.com/cefsharp/CefSharp.MinimalExample

Make sure to read the Release notes at https://github.com/cefsharp/CefSharp/releases/tag/v73.1.130

For details on the new versioning scheme please see https://github.com/cefsharp/CefSharp/issues/2706

Will leave this open for a little while before closing.
